/* eslint-disable no-unused-vars */

export enum GROUP {
  NAMESPACED = 'group',

  GETTER_GET_LIST_GROUP = 'GETTER_GET_LIST_GROUP',
  GETTER_GET_TOTAL_GROUP = 'GETTER_GET_TOTAL_GROUP',
  GETTER_GET_GROUP_STATE = 'GETTER_GET_GROUP_STATE',

  ACTION_ADD_VOTE_TO_GROUP = 'ACTION_ADD_VOTE_TO_GROUP',
  ACTION_TOGGLE_GROUP_STATE = 'ACTION_TOGGLE_GROUP_STATE',

  MUTATION_UPDATE_GROUP_VOTE = 'MUTATION_UPDATE_GROUP_VOTE',
  MUTATION_ADD_VOTE = 'MUTATION_ADD_VOTE',
}
